### PR TITLE
introduced random_bytes for secure random generation.

### PR DESCRIPTION
**Pull request by 0xcrypto**
Security fix for vulnerability reported at https://huntr.dev/bounties/6-other-online-invoicing-system/

### CODE REVIEW

**Comment by bigprof** [comment]
> 
> 
> Security fix for vulnerability reported at https://huntr.dev/bounties/6-other-online-invoicing-system/

Thank you for your suggested fix, which I appreciate and acknowledge. Due to the nature of OIM, being a generated app made by AppGini, I plan to apply the fix to the generator application itself soon.

**Comment by 0xcrypto** [comment]
Hi @bigprof, is it open source? If so, I can test it for more bugs and issues. Can you validate my report  https://huntr.dev/bounties/6-other-online-invoicing-system/ on huntr.dev? It will help me get a bounty and encourage me to submit more reports and fixes. Thanks.

**Comment by bigprof** [comment]
> 
> 
> Hi @bigprof, is it open source? If so, I can test it for more bugs and issues. Can you validate my report https://huntr.dev/bounties/6-other-online-invoicing-system/ on huntr.dev? It will help me get a bounty and encourage me to submit more reports and fixes. Thanks.

AppGini itself (the generator) is not open source. But I just confirmed the issue is valid on hunter.dev now.

**Comment by 0xcrypto** [comment]
> > Hi @bigprof, is it open source? If so, I can test it for more bugs and issues. Can you validate my report https://huntr.dev/bounties/6-other-online-invoicing-system/ on huntr.dev? It will help me get a bounty and encourage me to submit more reports and fixes. Thanks.
> 
> AppGini itself (the generator) is not open source. But I just confirmed the issue is valid on hunter.dev now.

thanks @bigprof. I will try finding bugs in the open sourced code.

**Pull request closed without merging**
